name: 'build-image'

on:
  push:
    paths:
      - 'Dockerfile'
      - 'docker-entrypoint.sh'
      - '.github/workflows/build-image.yaml'
      - 'requirements.txt'
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: get version of vdirsyncer from requirements.txt
        run: |
          VERSION=$( perl -ne 'print "$1\n" if m/^\s*vdirsyncer\s==\s*([\d.-]+)\s*$/;' requirements.txt
          echo "VDS_VERSION=$VERSION" >> "$GITHUB_ENV"
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ghcr.io/klaernie/vdirsyncer:latest
            ghcr.io/klaernie/vdirsyncer:$VDS_VERSION
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
