name: 'build-image'

on:
  push:
    paths:
      - 'Dockerfile'
      - 'docker-entrypoint.sh'
      - '.github/workflows/build-image.yaml'
    branches:
    - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ghcr.io/klaernie/vdirsyncer:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
